### ISSUE TITLE
HTTPS Over HTTP Proxy Tunneling Issue

### ISSUE THREAD

**Issue by mephicide** [googleapis/node-gtoken#131]
#### Environment details

  - OS: Ubuntu Linux 16.04
  - Node.js version: 8.10.0
  - npm version: 5.10.0
  - `gtoken` version:  2.3.0

#### Steps to reproduce

  1. Be behind a corporate proxy doing HTTPS over HTTP tunneling.  The HTTPS_PROXY environment variable will be set to http://xxxxxx:8080 or some other unsecured port to capture local traffic for retention.
  2. Use Google Dialogflow 0.5.0, 0.6.0 or other Google Cloud Service library that relies on google-gax 0.17.1 -> google-auth-library 1.6.1 -> gtoken 2.3.0 in its dependency tree as determined by `npm ls gtoken`
3. Notice that there will be an error from openssl dumped to the console along the lines of "invalid protocol".  (One example is Auth error:Error: write EPROTO 140533291190080:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:)

I am not an expert in the Google API architecture, but it appears that the issue is caused when GToken uses axios to facilitate its underlying HTTPS connection to authenticate with Google APIs.  Axios documentation covers a lot of ground, but the basic feature necessary is to not assume that the proxy protocol is HTTPS just because the destination URL is.  Maybe there is a way to use Axios differently in this case?  Maybe use whatever HTTP library other areas of the google-gax / grpc projects use to successfully capture project metadata etc. through a proxy configured this way?  Maybe this problem has already been fixed?  I don't know, but hopefully this report helps someone other than me :smile:

**Comment by JustinBeckwith** [comment]
Greetings @mephicide! Could you try installing this library directly from master, and seeing if you still have the issue?  We made some changes in here recently that could fix the glitch.

**Comment by mephicide** [comment]
Hey @JustinBeckwith!  I see your name all over these projects I am working with; you're doing a great job, and I am sure you are busy, so thanks for taking the time to help :smile: 

I installed the library directly to my top-level project by adding a dependency to my local `node-gtoken` codebase in my project's `package.json`, which appears to have overridden the transitive dependency as reported by `npm ls gtoken` which shows:

```
├─┬ dialogflow@0.6.0
│ └─┬ google-gax@0.17.1
│   └─┬ google-auth-library@1.6.1
│     └── gtoken@2.3.0  -> /home/user/node-gtoken deduped
└── gtoken@2.3.0  -> /home/user/node-gtoken
```
My local copy of `node-gtoken` is on rev. `2f22c3a350c7a672a3cdac532c77563cdd3e0446` which shows a recent commit from Nov. 19th 2018.  Let me know if I have set everything up correctly!

Unfortunately, I am still seeing the same SSL issue.  I have confirmed that overriding my dependency on `axios` to use one where I have edited their code to tunnel HTTPS over HTTP produces the expected results, so the issue I am experiencing is still due to the same underlying use of axios from what I can tell.

**Comment by JustinBeckwith** [comment]
@stephenplusplus another proxy issue for you 🍔

**Comment by hiranya911** [comment]
Just ran into this while trying to use Cloud Firestore (see https://github.com/googleapis/google-auth-library-nodejs/issues/571 and https://github.com/googleapis/nodejs-firestore/issues/493 for full context). After a bit of experimenting, here's what I've found out:

* v2.3.0 of the library uses Axios, which has a known issue with HTTPS proxy discovery. This breaks the library when `HTTPS_PROXY` env variable is set.
* v2.3.1 uses gaxios, which supports proxy servers correctly, but one must set the `https_proxy` environment variable (i.e. as opposed to `HTTPS_PROXY`):

https://github.com/JustinBeckwith/gaxios/blob/db3b02b36b78e70ee1d93ad0485826fd7c058d67/src/gaxios.ts#L134-L142

**Comment by JustinBeckwith** [comment]
👋 The issue with capitalization was fixed here:
https://github.com/JustinBeckwith/gaxios/commit/b5edd2de974545ec7c401e358efbd99271663fd0

And a new release was cut :)
