### ISSUE TITLE
For v2.3.0 -> v2.3.1, the inclusion of gaxios was temporarily breaking.

### ISSUE THREAD

**Issue by radichc** [googleapis/node-gtoken#151]
For three days (Dec 11 - Dec 14), installing gtoken would install [gaxios v1.0.3](https://github.com/JustinBeckwith/gaxios/releases/tag/v1.0.3), which incorrectly returns JSON responses as a string, and not the parsed object (fixed in v1.0.4).

This broke google authentication for us until today. Just a heads up for anyone else that may be having authentication issues.

**Comment by JustinBeckwith** [comment]
Yeah, apologies about that one :/ . We fixed it pretty quickly (a few hours), but yeah new installs were broken for a bit. Should be all good now!
