### ISSUE TITLE
v2.3.3 breaks as dependency of google-auth-library 1.6.1

### ISSUE THREAD

**Issue by amrsh** [googleapis/node-gtoken#198]
#### Environment details

  - OS: Google App Engine Flex (Debian 4.9.144-3.1)
  - Node.js version: 6.11.1
  - npm version: 3.10.10
  - `gtoken` version: 2.3.3

#### Steps to reproduce

  1. npm install node app using google-auth-library 1.6.1, which has dependency "gtoken": "^2.3.0", which since March 13 2019 pulls in v2.3.3
  2. call auth.JWT.authorize(callback) in node app
  3. receive below error, resolvable by manually requiring gtoken 2.3.0

TypeError: URL is not a constructor, at Gaxios.validateOpts (/app/node_modules/gaxios/build/src/gaxios.js:126:27), at Gaxios.<anonymous (/app/node_modules/gaxios/build/src/gaxios.js:61:25), at next (native), at /app/node_modules/gaxios/build/src/gaxios.js:19:71, at __awaiter (/app/node_modules/gaxios/build/src/gaxios.js:15:12), at Gaxios.request (/app/node_modules/gaxios/build/src/gaxios.js:60:16), at Object.<anonymous> (/app/node_modules/gaxios/build/src/index.js:38:33), at next (native), at /app/node_modules/gaxios/build/src/index.js:19:71, at __awaiter (/app/node_modules/gaxios/build/src/index.js:15:12), at Object.request (/app/node_modules/gaxios/build/src/index.js:37:12), at GoogleToken.<anonymous> (/app/node_modules/gtoken/build/src/index.js:191:29), at next (native), at /app/node_modules/gtoken/build/src/index.js:13:71, at __awaiter (/app/node_modules/gtoken/build/src/index.js:9:12), at GoogleToken.requestToken (/app/node_modules/gtoken/build/src/index.js:179:16)], message=URL is not a constructor

**Comment by callmehiphop** [comment]
@amrsh this is probably not the solution you're looking for, but you might want to just upgrade your Node version to >= 8. v6 officially went EOL last week, so I'm not sure if this is something that will get fixed.

**Comment by amrsh** [comment]
Yep, it's on the list for us to update node and all dependencies. But not sure this is related to the node version, and regardless, not good SemVer to have an existing functional package break, right?

**Comment by callmehiphop** [comment]
@amrsh yeah I totally agree and I apologize that you ran into this. I need to dig in a little deeper to see how this snuck in, but pretty sure `URL` in its current form wasn't added until `6.13.x`, so I'm not entirely sure why we were even using it.

**Comment by amrsh** [comment]
@callmehiphop much appreciated. Mostly wanted to post this issue to have Google index so others facing the same error might avoid the many hours it took for me to isolate to this lib :-)

**Comment by callmehiphop** [comment]
@amrsh much appreciated, thanks a ton!
