### ISSUE TITLE
4.1.2 breaks our build  with " error TS1086: An accessor cannot be declared in an ambient context."

### ISSUE THREAD

**Issue by gae123** [googleapis/node-gtoken#244]
We do not use gtoken directly and this started happening just after 4.1.2 rolled out. It seems to be a very similar issue we reported [here](https://github.com/googleapis/gax-nodejs/issues/642) for google-gax.

```
.../node_modules/gtoken/build/src/index.d.ts:32:9 - error TS1086: An accessor cannot be declared in an ambient context.

32     get accessToken(): string | undefined;
           ~~~~~~~~~~~

.../node_modules/gtoken/build/src/index.d.ts:33:9 - error TS1086: An accessor cannot be declared in an ambient context.

33     get idToken(): string | undefined;
           ~~~~~~~

.../node_modules/gtoken/build/src/index.d.ts:34:9 - error TS1086: An accessor cannot be declared in an ambient context.

34     get tokenType(): string | undefined;
           ~~~~~~~~~

.../node_modules/gtoken/build/src/index.d.ts:35:9 - error TS1086: An accessor cannot be declared in an ambient context.

35     get refreshToken(): string | undefined;
           ~~~~~~~~~~~~

```

Our environment:
```
$ node --version
v10.16.2
$ yarn --version
1.17.3
$ tsc --version
Version 3.5.3
```

Workaround:
In package.json add:
```
"resolutions": {
    "gtoken": "4.1.1"
  }
```

**Comment by gae123** [comment]
It seems that in 4.1.2 you upgraded the typescript compiler to 3.7.0 from 3.6.0 and this generates type definition file that is not working with us who still use earlier  versions.

**Comment by victorbadila** [comment]
Just got this problem in one of my builds today, can confirm.

**Comment by FSou1** [comment]
Same for me. Started to receive this error once installed the `firebase-admin` package.

**Comment by JustinBeckwith** [comment]
Greetings folks!  Can I ask - what version of TypeScript are you trying to use?  From what I can tell in the TypeScript release notes, this should have been a forward compatible change from 3.5:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#class-field-mitigations

**Comment by gae123** [comment]
Justin ours is 3.5.3. I have added versions in this or the sister google-gax ticket. (Sorry on my mobile right now)

**Comment by FSou1** [comment]
I tried to use 3.5.3 also. Looks like we should use 3.7, but it doesn't allow to compile Angular 8 app, which compiler depends on < 3.6 version.

**Comment by JustinBeckwith** [comment]
Thanks folks, after asking I ran into the gax bug and saw this info there too (apologies).  We're workin on a plan....

**Comment by alexander-fenster** [comment]
Hi folks, we just decided to rollback to TypeScript `~3.6.0` (will be in `gtoken` `4.1.3`). Hope that helps.

**Comment by BorntraegerMarc** [comment]
@alexander-fenster just to say that v4.1.3 isn't available on npm at the moment. Not sure if you intended to do a release yet

**Comment by iisy-client-releases** [comment]
@alexander-fenster build fails also for all kinds of @google-cloud/ apis. Any further informations about v4.1.3?

**Comment by alexander-fenster** [comment]
@iisy-client-releases @BorntraegerMarc 4.1.3 is there now, can you please check?

**Comment by BorntraegerMarc** [comment]
> @iisy-client-releases @BorntraegerMarc 4.1.3 is there now, can you please check?

seems to work. thanks!

**Comment by victorbadila** [comment]
I confirm that my projects builds now work for me as well

**Comment by iisy-client-releases** [comment]
Yes. Works. Thanks guys.

**Comment by alexander-fenster** [comment]
Thanks for confirming!

**Comment by Nyeedz** [comment]
> Yes. Works. Thanks guys.

i'm having the same error here

![image](https://user-images.githubusercontent.com/17225811/71836917-ecd61400-3093-11ea-9681-4a028153b7a7.png)

**Comment by eng-dibo** [comment]
same for me with `firebase-functions` 
https://github.com/firebase/firebase-functions/issues/667

**Comment by alexander-fenster** [comment]
@eng-dibo Since the time it was first reported, all major libraries updated TypeScript version they use, so we are now using `^3.8.3` as well. These errors should go away if you update TypeScript.

**Comment by eng-dibo** [comment]
good news, I will try this.
