### ISSUE TITLE
Vulnerability in node-forge dependency

### ISSUE THREAD

**Issue by e-duran** [googleapis/node-gtoken#409]
A dependency of node-gtoken, the node-forge package, has a vulnerability which is fixed in version 1.0.0 (or later). The vulnerability is rated as low severity but it'd be nice to get it fix nonetheless since this affects other libraries upstream that are widely used, for instance, googleapis.
node-forge is a dependency via the google-p12-pem package, which has released version 3.1.3 with the patched version of the package. Updating node-gtoken to use version 3.1.3 of google-p12-pem should remove the vulnerability.

**Comment by SurferJeffAtGoogle** [comment]
>A dependency of node-gtoken, the node-forge package, has a vulnerability which is fixed in version 1.0.0 (or later). The vulnerability is rated as low severity but it'd be nice to get it fix nonetheless since this affects other libraries upstream that are widely used, for instance, googleapis.
> node-forge is a dependency via the google-p12-pem package, which has released version 3.1.3 with the patched version of the package. Updating node-gtoken to use version 3.1.3 of google-p12-pem should remove the vulnerability.

This matches my understanding, but I don't understand what this issue is requesting.  This library does not include a package-lock.json, and the package.json will bring in versien 3.1.3 of google-p12-pem.  https://github.com/googleapis/node-gtoken/blob/edebd295bbda1ab38c9e9dfee97766f3d7a2f2e8/package.json#L43

**Comment by e-duran** [comment]
Sorry, my bad. I didn't realize that yarn failed to upgrade google-p12-pem to its latest version even when I upgraded googleapis to a new major version. I'm probably lacking some understanding of how yarn resolves transitive version but the workaround was to delete google-p12-pem entry in my yarn.lock and rerun install
