### ISSUE TITLE
Stop using buffer-equal-constant-time

### ISSUE THREAD

**Issue by idoshamun** [googleapis/node-gtoken#451]
I noticed you use buffer-equal-constant-time indirectly through jws and gtoken.
buffer-equal-constant-time is a legacy and unsupported package since 2017. (https://github.com/salesforce/buffer-equal-constant-time/issues/6)
It causes some issues in combination with docker and some other environments.
I'd appreciate if you can consider switching it.
A solid alternative for jwt purposes is [fast-jwt](https://github.com/nearform/fast-jwt).

I'm willing to work on it.

Related to https://github.com/googleapis/google-auth-library-nodejs/issues/1544

**Comment by ddelgrosso1** [comment]
@idoshamun thank you for opening this issue. It seems like the better place to fix this would be in `node-jwa` which is what is actually importing `buffer-equal-constant-time`. It looks like there is already an open issue there as well: https://github.com/auth0/node-jwa/issues/46.
