### ISSUE TITLE
Favor `undefined` over `null`

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/node-gtoken#60]
There are a bunch of places in the API where we use `null | undefined`.  There's almost never a good reason to use null, so lets change the API to only speak in terms of undefined.

**Comment by ofrobots** [comment]
Not to be pedantic, I disagree with " There's almost never a good reason to use null". I suggest reading http://thecodelesscode.com/case/6. 

My personal philosophy has been that `undefined` should not be be assigned or returned by user code. `null` is a good empty value. `undefined` represents even more emptiness – it is the lack of a value.

The reality of a given code-base and legacy might dictate different outcomes from the ideal described above though.

**Comment by JustinBeckwith** [comment]
> My personal philosophy has been that undefined should not be be assigned or returned by user code. 

Interesting!  This is a great discussion topic, and I'm not sure if it's a place where we (Google) have an official policy or anything.  I tend to find `null` in JavaScript a bizarre beast.  The whole `typeof null === 'object'` thing trips a lot of people up.  I see what you mean with the whole "not yet defined" as opposed to "defined then blanked out".

With this particular API - there are some interesting problems with the API design that lead to nulls.  The way we assign values to the object during `getToken` results in hard to track side effects, and feels like general poor design pattern.  I suspect if we addressed that - the reasons for using null here would go away.  There's really no reason for this API to be stateful. 

Let me play around and see what happens :)

**Comment by JustinBeckwith** [comment]
Upon further investigation - there's really no good reason to make a change here.
